#!bash
#
# Bash completion support for Bitbake
#
# Copyright (C) 2014 Sergio Prado <sergio.prado@e-labworks.com>
# Distributed under the MIT License (MIT)
#

_bitbake()
{
    local cur prev opts_short opts_long tasks recipes bbfile_entry recipe
    local ui bblayers_conf bblayers_md5 bblayers_bbfile bblayers_recipes
    local recipe_path

    COMPREPLY=()

    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    opts_short="-h -b -k -a -f -c -C -r -R -v -D -n -S -p -s -e -g -I \
                -l -P -u -t -B -m"

    opts_long="--version --help --buildfile= --continue --tryaltconfigs \
               --force --cmd= --clear-stamp= --read= --postread= --verbose \
               --debug --dry-run --dump-signatures= --parse-only \
               --show-versions --environment --graphviz --ignore-deps= \
               --log-domains= --profile --ui= --servertype= --token= \
               --revisions-changed --server-only --bind= --no-setscene \
               --remote-server= --kill-server --observe-only \
               --status-only"

    tasks="build bundle_initramfs checkuri checkuriall clean cleanall \
           cleansstate compile configure devshell fetch fetchall \
           install listtasks package package_setscene \
           package_write_rpm package_write_rpm_setscene packagedata \
           packagedata_setscene patch populate_lic \
           populate_lic_setscene populate_sdk populate_sysroot \
           populate_sysroot_setscene rootfs unpack compile_ptest_base \
           configure_ptest_base diffconfig install_ptest_base \
           menuconfig patch"

    ui="knotty hob depexp"

    if [[ "$prev" == "=" ]]; then
        prev="${COMP_WORDS[COMP_CWORD - 2]}"
    elif [[ "$cur" == "=" ]]; then
        cur=""
    fi

    case "$prev" in
       
        "-c"|"--cmd"|"-C"|"--clear-stamp")
            COMPREPLY=( $(compgen -W "${tasks}" -- ${cur}) )
            return 0
        ;;
        
        "-u"|"--ui")
            COMPREPLY=( $(compgen -W "${ui}" -- ${cur}) )
            return 0
        ;;

    esac

    case "$cur" in

        "--"*)
            COMPREPLY=( $(compgen -W "${opts_long}" -- ${cur}) )
            if [[ ${#COMPREPLY[@]} == 1 && ${COMPREPLY[0]} == "--"*"=" ]] ; then
                compopt -o nospace
            fi
            return 0
        ;;

        "-"*)
            COMPREPLY=( $(compgen -W "${opts_short}" -- ${cur}) )
            return 0
        ;;

    esac

    bblayers_conf="conf/bblayers.conf"
    bblayers_md5=".bblayers.conf.md5"
    bblayers_bbfile=".bblayers.bbfile"
    bblayers_recipes=".bblayers.recipes"

    _parse_recipes () {
	    echo `bitbake -e | grep "^BBFILES=" | cut -d "=" -f 2 | sed -e 's/"//g'` > $bblayers_bbfile
	    for bbfile_entry in `cat $bblayers_bbfile`; do
	        if [ "${bbfile_entry%.bbappend}" = "${bbfile_entry}" ]; then
		        echo $bbfile_entry
	        fi
	    done | while read recipe_path; do
	        recipe="${recipe_path##*/}"
	        recipe="${recipe%%_*.bb}"
	        recipe="${recipe%%.bb}"
	        if [ "$recipe" != "*" ]; then
		        echo $recipe
	        fi
	    done > $bblayers_recipes
        rm -Rf $bblayers_bbfile
    }

    if [ ! -e $bblayers_conf ]; then
        return 0;
    fi

    if [ "$prev" = "bitbake" -a "$cur" = "" ]; then
	    _parse_recipes
    fi

    md5sum --quiet --status -c $bblayers_md5 2>/dev/null
    if [ $? != 0 -o ! -e $bblayers_recipes ]; then
         md5sum $bblayers_conf > $bblayers_md5
	    _parse_recipes
    fi

    recipes=`cat $bblayers_recipes`

    COMPREPLY=( $(compgen -W "${recipes}" -- ${cur}) )
    return 0
}
complete -F _bitbake bitbake
